services:
  - type: web
    name: aischool
    env: node
    buildCommand: npm install && npm run db:generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: file:./data/aischool.db
      - key: NEXTAUTH_SECRET
        value: your-nextauth-secret-here
      - key: NEXTAUTH_URL
        value: https://aischool-u7d7.onrender.com
    healthCheck:
      path: /
      initialDelaySeconds: 60
      timeoutSeconds: 10
      periodSeconds: 30
      failureThreshold: 5
    disk:
      name: data
      mountPath: /opt/render/project/data
      sizeGB: 1