services:
  - type: web
    name: aischool
    env: node
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: file:./data/aischool.db
      - key: NEXTAUTH_SECRET
        value: your-nextauth-secret-here
      - key: NEXTAUTH_URL
        value: https://aischool.onrender.com
      - key: ZAI_API_KEY
        value: your-z-ai-api-key-here
    healthCheck:
      path: /api/health
      initialDelaySeconds: 60
      timeoutSeconds: 10
      periodSeconds: 30
      failureThreshold: 5
    disk:
      name: data
      mountPath: /opt/render/project/data
      sizeGB: 1