services:
  - type: web
    name: aischool
    env: node
    # هذا الأمر سيقوم بتثبيت الحزم ثم تشغيل السكريبت المخصص للبناء
    buildCommand: npm install && npm run render-build
    # سيقوم Render بتشغيل هذا الأمر بعد البناء لبدء التطبيق
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: file:./data/aischool.db
      - key: NEXTAUTH_SECRET
        value: your-nextauth-secret-here
      - key: NEXTAUTH_URL
        value: https://aischool.onrender.com
    healthCheck:
      path: /
      initialDelaySeconds: 30
      timeoutSeconds: 10
      periodSeconds: 30
      failureThreshold: 5
    disk:
      name: data
      mountPath: /opt/render/project/data
      sizeGB: 1
