services:
  - type: web
    name: aischool
    env: node
    # Use a custom deploy script to ensure all steps run correctly.
    buildCommand: npm run deploy
    # Render will run this command after the build to start the application.
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: file:./data/aischool.db
      - key: NEXTAUTH_SECRET
        value: your-nextauth-secret-here
      - key: NEXTAUTH_URL
        value: https://aischool.onrender.com
    healthCheck:
      path: /
      initialDelaySeconds: 30
      timeoutSeconds: 10
      periodSeconds: 30
      failureThreshold: 5
    disk:
      name: data
      mountPath: /opt/render/project/data
      sizeGB: 1
