services:
  - type: web
    name: aischool
    env: node
    plan: free # Or your preferred plan
    buildCommand: npm run render-build
    preDeployCommand: npm run db:migrate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      # DATABASE_URL should be set as a secret in the Render dashboard
      - key: DATABASE_URL
        sync: false
      # NEXTAUTH_SECRET should be set as a secret in the Render dashboard
      - key: NEXTAUTH_SECRET
        sync: false
      - key: NEXTAUTH_URL
        value: https://aischool-u7d7.onrender.com
      # PGSSLMODE is required for secure connections to Supabase
      - key: PGSSLMODE
        value: require
